handler:
  api:
    telegram: /tg

service:
  telegram:
    webhook_link: ~

  vk: ~

  keypads:
    source: &source
      last_fm: &last_fm
        text: last fm
        callback_data: lastFm
      ya_music: &ya_music
        text: ya music
        callback_data: yaMusic
      all: &all
        text: similar
        callback_data: all

    vk_submenu: &vk_submenu
      vk_submenu_button:
        text: vk
        callback_data: vkSubmenu
      vk_auth:
        text: authorize
        callback_data: vkAuth
      vk_recommendation:
        text: recommendations
        callback_data: vkRecommendations
      vk_user_playlist:
        text: playlists
        callback_data: vkPlaylists

    main_menu:
      main_menu_button:
        text: main menu
        callback_data: mainMenu
      vk_submenu: *vk_submenu

    search_menu: *source

    song_menu:
      song_menu_button:
          text: song menu
          callback_data: songMenu
      delete:
          text: delete
          callback_data: delete
      similar:
          text: similar
          callback_data: sim
      best:
          text: top songs
          callback_data: top